name: Build Package

on:
  repository_dispatch:
    types: [new-release, rebuild]

env:
    PAT: ${{secrets.PAT}}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Update system and install dependencies
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm --quiet
          pacman -S base-devel git sudo pacman-contrib --noconfirm --quiet

      - name: Add a Build user
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers
          
      - name: Build PKG
        run: |
          su builder -c "git clone https://github.com/materialgram/materialgram-bin /home/builder/build && cd /home/builder/build \
                         && sed -i "s/pkgver=.*/pkgver=${{ github.event.client_payload.tagname }}/" PKGBUILD \
                         && sed -i "s/pkgrel=.*/pkgrel=${{ github.event.client_payload.pkgrel }}/" PKGBUILD \
                         && updpkgsums && makepkg --syncdeps --noconfirm --needed && rm *debug*"

      - name: Set filename as variable
        run: echo "FILENAME=$(basename /home/builder/build/*.zst)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILENAME }}
          path: /home/builder/build/*.zst
      
      - name: Upload artifact to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/')
        with:
          name: ${{ env.FILENAME }}
          token: ${{ secrets.PAT }}
          files: /home/builder/build/${{ env.FILENAME }}
  
  update-pkg-repo:
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: materialgram/arch
        token: ${{ secrets.repopat }}
    
    - name: do the things
      run: |
        rm m*
        TAG=$(curl -s https://api.github.com/repos/materialgram/materialgram-bin/releases/latest | jq -r '.tag_name')
        BIN=$(curl -s https://api.github.com/repos/materialgram/materialgram-bin/releases/latest | jq -r '.assets[] | .name' | grep zst)
        URL=https://github.com/materialgram/materialgram-bin/releases/download/${TAG}/${BIN}
        wget $URL
        repo-add materialgram.db.tar.gz *zst
        git config --global user.email "omansh11597@gmail.com" && git config --global user.name "Omansh Krishn" && git add . && git commit -s -m "materialgram: Update ${{ github.event.client_payload.tagname }}-${{ github.event.client_payload.pkgrel }}"
        git push
