name: Build Package

on:
  push:
    branches:
      - main

env:
    PAT: ${{secrets.PAT}}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Update system and install dependencies
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          pacman -Syu --noconfirm --quiet
          pacman -S base-devel git sudo github-cli --noconfirm --quiet

      - name: Build package
        run: |
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" | tee -a /etc/sudoers
          su builder -c "git clone https://github.com/materialgram/materialgram-bin /home/builder/build && cd /home/builder/build && makepkg --syncdeps --noconfirm --needed"

      - name: Set filename as variable
        run: echo "FILENAME=$(basename /home/builder/build/*.zst)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILENAME }}
          path: /home/builder/build/*.zst
      
      - name: UPLOAD TO GITHUB RELEASES
        run: |
          echo $PAT | gh auth login --with-token
          export VERSION=$(cat /home/builder/build/PKGBUILD | grep 'pkgver=' | cut -d'=' -f2)
          gh release create ${VERSION} /home/builder/build/${{ env.FILENAME }} --repo materialgram/materialgram-bin --notes ${VERSION}

